version: '3.3'

services:
  application:
    container_name: application_container
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: database_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shop
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: database_admin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
